services:
  traefik:
    image: traefik:v3.3
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    networks:
      - web
      - internal
    command:
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.leresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.leresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.leresolver.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.leresolver.acme.storage=/letsencrypt/acme.json"
  
  api:
    image: ghcr.io/danny-avila/librechat-dev-api:latest
    container_name: LibreChat-API
    ports:
      - 3080:3080
    depends_on:
      - mongodb
      # - rag_api
    restart: always
    extra_hosts:
    - "host.docker.internal:host-gateway"
    env_file:
      - .api.env
    networks:
      - web
      - internal
    volumes:
      - ./librechat.yaml:/app/librechat.yaml
      - api_images:/app/client/public/images
      - api_logs:/app/api/logs
      - api_uploads:/app/uploads
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.librechat.rule=Host(`${URL_API}`)"
      - "traefik.http.routers.librechat.entrypoints=websecure"
      - "traefik.http.routers.librechat.tls.certresolver=leresolver"
      - "traefik.http.services.librechat.loadbalancer.server.port=3080"

  mongodb:
    container_name: chat-mongodb
    image: mongo
    restart: always
    networks:
      - internal
    volumes:
      - mongodb_data:/data/db
    command: mongod --noauth
  
  meilisearch:
    container_name: chat-meilisearch
    image: getmeili/meilisearch:v1.12.3
    restart: always
    environment:
      - SEARCH=true
      - MEILI_HOST=http://meilisearch:7700
      - MEILI_NO_ANALYTICS=true
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
    networks:
      - internal
    volumes:
      - meilisearch_data:/meili_data
  
  # vectordb:
  #   image: ankane/pgvector:latest
  #   environment:
  #     POSTGRES_DB: mydatabase
  #     POSTGRES_USER: myuser
  #     POSTGRES_PASSWORD: mypassword
  #   restart: always
  #   volumes:
  #     - pgdata2:/var/lib/postgresql/data
  
  # rag_api:
  #   image: ghcr.io/danny-avila/librechat-rag-api-dev-lite:latest
  #   restart: always
  #   depends_on:
  #     - vectordb
  #   env_file:
  #     - .rag_api.env
 
networks:
  internal:
    external: false
  web:
    external: true

volumes:
  api_images:
  api_logs:
  api_uploads:
  mongodb_data:
  meilisearch_data:
  # pgdata2:
